### ISSUE TITLE
Create Bars Cards Div

### ISSUE THREAD

**Issue by antger78** [AdamDagi/project-01#3]
## Create Bars Cards Div
- [x] Create Div container to hold all cards
- [x] Create function that generates the items after the button click (#2 )
- [x] Created 6 cards
- [ ] 
-https://developers.google.com/maps/documentation/places/web-service/search
![image](https://user-images.githubusercontent.com/90581274/141223250-fc667883-fddc-45c9-9109-fc29c17f015f.png)

**Comment by AdamDagi** [comment]
Finished
